// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package routing

import "github.com/browningluke/opnsense-go/pkg/api"

const routingReconfigureEndpoint = "/routing/settings/reconfigure"

// Controller for routing
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
